architecture: standalone
image:
  tag: 7.0.5-debian-11-r15
master:
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 1Gi
  service:
    type: "ClusterIP"